from typing import Dict, NamedTuple, Set, Optional


class AnimalWellLocationData(NamedTuple):
    region: str
    er_region: str  # entrance rando region
    location_group: Optional[str] = None


location_base_id = 11553377

location_table: Dict[str, AnimalWellLocationData] = {
    "Beneath the Well - [Powered Secret Room] Chest": AnimalWellLocationData("Beneath the Well", "Beneath the Well Back"),
    "Beneath the Well - [Entryway] Chest": AnimalWellLocationData("Beneath the Well", "Beneath the Well Main"),
    "Beneath the Well - [Third Room] Beneath Platform Chest": AnimalWellLocationData("Beneath the Well", "Beneath the Well Main"),
    "Beneath the Well - [Third Room] Tentacle Chest": AnimalWellLocationData("Beneath the Well", "Beneath the Well Main"),
    "Beneath the Well - [Entryway] Obscured Behind Waterfall": AnimalWellLocationData("Beneath the Well", "Beneath the Well Main"),
    "Beneath the Well - [Save Room] Upper Floor Chest 1": AnimalWellLocationData("Beneath the Well", "Beneath the Well Back"),
    "Beneath the Well - [Save Room] Upper Floor Chest 2": AnimalWellLocationData("Beneath the Well", "Beneath the Well Back"),
    "Beneath the Well - [Second Room] Underwater Chest": AnimalWellLocationData("Beneath the Well", "Beneath the Well Main"),
    "Beneath the Well - [Back Corridor] Right Secret": AnimalWellLocationData("Beneath the Well", "Beneath the Well Main"),
    "Beneath the Well - [Back Corridor] Left Secret": AnimalWellLocationData("Beneath the Well", "Beneath the Well Main"),
    "Beneath the Well - [Second Room] Obscured Behind Waterfall": AnimalWellLocationData("Beneath the Well", "Beneath the Well Main"),
    "Beneath the Well - [Side Room] Chest By Pots": AnimalWellLocationData("Beneath the Well", "Beneath the Well Back"),
    "Beneath the Well - [Side Room] Chest By Phrends": AnimalWellLocationData("Beneath the Well", "Beneath the Well Back"),
    "Beneath the Well - [Second Room] Page": AnimalWellLocationData("Beneath the Well", "Beneath the Well Main"),
    "Dark Tomb Checkpoint - [Passage To Dark Tomb] Page Pickup": AnimalWellLocationData("Overworld", "Dark Tomb Checkpoint"),
    "Cathedral - [1F] Guarded By Lasers": AnimalWellLocationData("Cathedral", "Cathedral"),
    "Cathedral - [1F] Near Spikes": AnimalWellLocationData("Cathedral", "Cathedral"),
    "Cathedral - [2F] Bird Room": AnimalWellLocationData("Cathedral", "Cathedral"),
    "Cathedral - [2F] Entryway Upper Walkway": AnimalWellLocationData("Cathedral", "Cathedral"),
    "Cathedral - [1F] Library": AnimalWellLocationData("Cathedral", "Cathedral"),
    "Cathedral - [2F] Library": AnimalWellLocationData("Cathedral", "Cathedral"),
    "Cathedral - [2F] Guarded By Lasers": AnimalWellLocationData("Cathedral", "Cathedral"),
    "Cathedral - [2F] Bird Room Secret": AnimalWellLocationData("Cathedral", "Cathedral"),
    "Cathedral - [1F] Library Secret": AnimalWellLocationData("Cathedral", "Cathedral"),
    "Dark Tomb - Spike Maze Near Exit": AnimalWellLocationData("Dark Tomb", "Dark Tomb Main"),
    "Dark Tomb - 2nd Laser Room": AnimalWellLocationData("Dark Tomb", "Dark Tomb Main"),
    "Dark Tomb - 1st Laser Room": AnimalWellLocationData("Dark Tomb", "Dark Tomb Main"),
    "Dark Tomb - Spike Maze Upper Walkway": AnimalWellLocationData("Dark Tomb", "Dark Tomb Main"),
    "Dark Tomb - Skulls Chest": AnimalWellLocationData("Dark Tomb", "Dark Tomb Upper"),
    "Dark Tomb - Spike Maze Near Stairs": AnimalWellLocationData("Dark Tomb", "Dark Tomb Main"),
    "Dark Tomb - 1st Laser Room Obscured": AnimalWellLocationData("Dark Tomb", "Dark Tomb Main"),
    "Guardhouse 2 - Upper Floor": AnimalWellLocationData("East Forest", "Guard House 2 Upper"),
    "Guardhouse 2 - Bottom Floor Secret": AnimalWellLocationData("East Forest", "Guard House 2 Lower"),
    "Guardhouse 1 - Upper Floor Obscured": AnimalWellLocationData("East Forest", "Guard House 1 East"),
    "Guardhouse 1 - Upper Floor": AnimalWellLocationData("East Forest", "Guard House 1 East"),
    "East Forest - Dancing Fox Spirit Holy Cross": AnimalWellLocationData("East Forest", "East Forest Dance Fox Spot", location_group="Holy Cross"),
    "East Forest - Golden Obelisk Holy Cross": AnimalWellLocationData("East Forest", "Lower Forest", location_group="Holy Cross"),
    "East Forest - Ice Rod Grapple Chest": AnimalWellLocationData("East Forest", "East Forest"),
    "East Forest - Above Save Point": AnimalWellLocationData("East Forest", "East Forest"),
    "East Forest - Above Save Point Obscured": AnimalWellLocationData("East Forest", "East Forest"),
    "East Forest - From Guardhouse 1 Chest": AnimalWellLocationData("East Forest", "East Forest Dance Fox Spot"),
    "East Forest - Near Save Point": AnimalWellLocationData("East Forest", "East Forest"),
    "East Forest - Beneath Spider Chest": AnimalWellLocationData("East Forest", "Lower Forest"),
    "East Forest - Near Telescope": AnimalWellLocationData("East Forest", "East Forest"),
    "East Forest - Spider Chest": AnimalWellLocationData("East Forest", "Lower Forest"),
    "East Forest - Lower Dash Chest": AnimalWellLocationData("East Forest", "Lower Forest"),
    "East Forest - Lower Grapple Chest": AnimalWellLocationData("East Forest", "Lower Forest"),
    "East Forest - Bombable Wall": AnimalWellLocationData("East Forest", "East Forest"),
    "East Forest - Page On Teleporter": AnimalWellLocationData("East Forest", "East Forest"),
    "Forest Belltower - Near Save Point": AnimalWellLocationData("East Forest", "Forest Belltower Lower"),
    "Forest Belltower - After Guard Captain": AnimalWellLocationData("East Forest", "Forest Belltower Upper"),
    "Forest Belltower - Obscured Near Bell Top Floor": AnimalWellLocationData("East Forest", "Forest Belltower Upper"),
    "Forest Belltower - Obscured Beneath Bell Bottom Floor": AnimalWellLocationData("East Forest", "Forest Belltower Main"),
    "Forest Belltower - Page Pickup": AnimalWellLocationData("East Forest", "Forest Belltower Main"),
    "Forest Grave Path - Holy Cross Code by Grave": AnimalWellLocationData("East Forest", "Forest Grave Path by Grave", location_group="Holy Cross"),
    "Forest Grave Path - Above Gate": AnimalWellLocationData("East Forest", "Forest Grave Path Main"),
    "Forest Grave Path - Obscured Chest": AnimalWellLocationData("East Forest", "Forest Grave Path Main"),
    "Forest Grave Path - Upper Walkway": AnimalWellLocationData("East Forest", "Forest Grave Path Upper"),
    "Forest Grave Path - Sword Pickup": AnimalWellLocationData("East Forest", "Forest Grave Path by Grave"),
    "Hero's Grave - Tooth Relic": AnimalWellLocationData("East Forest", "Hero Relic - East Forest"),
    "Fortress Courtyard - From East Belltower": AnimalWellLocationData("East Forest", "Fortress Exterior from East Forest"),
    "Fortress Leaf Piles - Secret Chest": AnimalWellLocationData("Eastern Vault Fortress", "Fortress Leaf Piles"),
    "Fortress Arena - Hexagon Red": AnimalWellLocationData("Eastern Vault Fortress", "Fortress Arena"),
    "Fortress Arena - Siege Engine/Vault Key Pickup": AnimalWellLocationData("Eastern Vault Fortress", "Fortress Arena", location_group="Bosses"),
    "Fortress East Shortcut - Chest Near Slimes": AnimalWellLocationData("Eastern Vault Fortress", "Fortress East Shortcut Lower"),
    "Eastern Vault Fortress - [West Wing] Candles Holy Cross": AnimalWellLocationData("Eastern Vault Fortress", "Eastern Vault Fortress", location_group="Holy Cross"),
    "Eastern Vault Fortress - [West Wing] Dark Room Chest 1": AnimalWellLocationData("Eastern Vault Fortress", "Eastern Vault Fortress"),
    "Eastern Vault Fortress - [West Wing] Dark Room Chest 2": AnimalWellLocationData("Eastern Vault Fortress", "Eastern Vault Fortress"),
    "Eastern Vault Fortress - [East Wing] Bombable Wall": AnimalWellLocationData("Eastern Vault Fortress", "Eastern Vault Fortress"),
    "Eastern Vault Fortress - [West Wing] Page Pickup": AnimalWellLocationData("Eastern Vault Fortress", "Eastern Vault Fortress"),
    "Fortress Grave Path - Upper Walkway": AnimalWellLocationData("Eastern Vault Fortress", "Fortress Grave Path Upper"),
    "Fortress Grave Path - Chest Right of Grave": AnimalWellLocationData("Eastern Vault Fortress", "Fortress Grave Path"),
    "Fortress Grave Path - Obscured Chest Left of Grave": AnimalWellLocationData("Eastern Vault Fortress", "Fortress Grave Path"),
    "Hero's Grave - Flowers Relic": AnimalWellLocationData("Eastern Vault Fortress", "Hero Relic - Fortress"),
    "Beneath the Fortress - Bridge": AnimalWellLocationData("Beneath the Vault", "Beneath the Vault Back"),
    "Beneath the Fortress - Cell Chest 1": AnimalWellLocationData("Beneath the Vault", "Beneath the Vault Back"),
    "Beneath the Fortress - Obscured Behind Waterfall": AnimalWellLocationData("Beneath the Vault", "Beneath the Vault Front"),
    "Beneath the Fortress - Back Room Chest": AnimalWellLocationData("Beneath the Vault", "Beneath the Vault Back"),
    "Beneath the Fortress - Cell Chest 2": AnimalWellLocationData("Beneath the Vault", "Beneath the Vault Back"),
    "Frog's Domain - Near Vault": AnimalWellLocationData("Frog's Domain", "Frog's Domain"),
    "Frog's Domain - Slorm Room": AnimalWellLocationData("Frog's Domain", "Frog's Domain"),
    "Frog's Domain - Escape Chest": AnimalWellLocationData("Frog's Domain", "Frog's Domain Back"),
    "Frog's Domain - Grapple Above Hot Tub": AnimalWellLocationData("Frog's Domain", "Frog's Domain"),
    "Frog's Domain - Above Vault": AnimalWellLocationData("Frog's Domain", "Frog's Domain"),
    "Frog's Domain - Main Room Top Floor": AnimalWellLocationData("Frog's Domain", "Frog's Domain"),
    "Frog's Domain - Main Room Bottom Floor": AnimalWellLocationData("Frog's Domain", "Frog's Domain"),
    "Frog's Domain - Side Room Secret Passage": AnimalWellLocationData("Frog's Domain", "Frog's Domain"),
    "Frog's Domain - Side Room Chest": AnimalWellLocationData("Frog's Domain", "Frog's Domain"),
    "Frog's Domain - Side Room Grapple Secret": AnimalWellLocationData("Frog's Domain", "Frog's Domain"),
    "Frog's Domain - Magic Orb Pickup": AnimalWellLocationData("Frog's Domain", "Frog's Domain"),
    "Librarian - Hexagon Green": AnimalWellLocationData("Library", "Library Arena", location_group="Bosses"),
    "Library Hall - Holy Cross Chest": AnimalWellLocationData("Library", "Library Hall", location_group="Holy Cross"),
    "Library Lab - Chest By Shrine 2": AnimalWellLocationData("Library", "Library Lab"),
    "Library Lab - Chest By Shrine 1": AnimalWellLocationData("Library", "Library Lab"),
    "Library Lab - Chest By Shrine 3": AnimalWellLocationData("Library", "Library Lab"),
    "Library Lab - Behind Chalkboard by Fuse": AnimalWellLocationData("Library", "Library Lab"),
    "Library Lab - Page 3": AnimalWellLocationData("Library", "Library Lab"),
    "Library Lab - Page 1": AnimalWellLocationData("Library", "Library Lab"),
    "Library Lab - Page 2": AnimalWellLocationData("Library", "Library Lab"),
    "Hero's Grave - Mushroom Relic": AnimalWellLocationData("Library", "Hero Relic - Library"),
    "Lower Mountain - Page Before Door": AnimalWellLocationData("Overworld", "Lower Mountain"),
    "Changing Room - Normal Chest": AnimalWellLocationData("Overworld", "Changing Room"),
    "Fortress Courtyard - Chest Near Cave": AnimalWellLocationData("Overworld", "Fortress Exterior near cave"),
    "Fortress Courtyard - Near Fuse": AnimalWellLocationData("Overworld", "Fortress Exterior from Overworld"),
    "Fortress Courtyard - Below Walkway": AnimalWellLocationData("Overworld", "Fortress Exterior from Overworld"),
    "Fortress Courtyard - Page Near Cave": AnimalWellLocationData("Overworld", "Fortress Exterior near cave"),
    "West Furnace - Lantern Pickup": AnimalWellLocationData("Overworld", "Furnace Fuse"),
    "Maze Cave - Maze Room Chest": AnimalWellLocationData("Overworld", "Maze Cave"),
    "Old House - Normal Chest": AnimalWellLocationData("Overworld", "Old House Front"),
    "Old House - Shield Pickup": AnimalWellLocationData("Overworld", "Old House Front"),
    "Overworld - [West] Obscured Behind Windmill": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [South] Beach Chest": AnimalWellLocationData("Overworld", "Overworld Beach"),
    "Overworld - [West] Obscured Near Well": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [Central] Bombable Wall": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [Northwest] Chest Near Turret": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [East] Chest Near Pots": AnimalWellLocationData("Overworld", "East Overworld"),
    "Overworld - [Northwest] Chest Near Golden Obelisk": AnimalWellLocationData("Overworld", "Overworld above Quarry Entrance"),
    "Overworld - [Southwest] South Chest Near Guard": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [Southwest] West Beach Guarded By Turret": AnimalWellLocationData("Overworld", "Overworld Beach"),
    "Overworld - [Southwest] Chest Guarded By Turret": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [Northwest] Shadowy Corner Chest": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [Southwest] Obscured In Tunnel To Beach": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [Southwest] Grapple Chest Over Walkway": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [Northwest] Chest Beneath Quarry Gate": AnimalWellLocationData("Overworld", "Overworld after Envoy"),
    "Overworld - [Southeast] Chest Near Swamp": AnimalWellLocationData("Overworld", "Overworld Swamp Lower Entry"),
    "Overworld - [Southwest] From West Garden": AnimalWellLocationData("Overworld", "Overworld Beach"),
    "Overworld - [East] Grapple Chest": AnimalWellLocationData("Overworld", "Overworld above Patrol Cave"),
    "Overworld - [Southwest] West Beach Guarded By Turret 2": AnimalWellLocationData("Overworld", "Overworld Beach"),
    "Overworld - [Southwest] Beach Chest Near Flowers": AnimalWellLocationData("Overworld", "Overworld Beach"),
    "Overworld - [Southwest] Bombable Wall Near Fountain": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [West] Chest After Bell": AnimalWellLocationData("Overworld", "Overworld Belltower"),
    "Overworld - [Southwest] Tunnel Guarded By Turret": AnimalWellLocationData("Overworld", "Overworld Tunnel Turret"),
    "Overworld - [East] Between Ladders Near Ruined Passage": AnimalWellLocationData("Overworld", "After Ruined Passage"),
    "Overworld - [Northeast] Chest Above Patrol Cave": AnimalWellLocationData("Overworld", "Upper Overworld"),
    "Overworld - [Southwest] Beach Chest Beneath Guard": AnimalWellLocationData("Overworld", "Overworld Beach"),
    "Overworld - [Central] Chest Across From Well": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [Northwest] Chest Near Quarry Gate": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [East] Chest In Trees": AnimalWellLocationData("Overworld", "Above Ruined Passage"),
    "Overworld - [West] Chest Behind Moss Wall": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [South] Beach Page": AnimalWellLocationData("Overworld", "Overworld Beach"),
    "Overworld - [Southeast] Page on Pillar by Swamp": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [Southwest] Key Pickup": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [West] Key Pickup": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [East] Page Near Secret Shop": AnimalWellLocationData("Overworld", "East Overworld"),
    "Overworld - [Southwest] Fountain Page": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [Northwest] Page on Pillar by Dark Tomb": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [Northwest] Fire Wand Pickup": AnimalWellLocationData("Overworld", "Upper Overworld"),
    "Overworld - [West] Page On Teleporter": AnimalWellLocationData("Overworld", "Overworld"),
    "Overworld - [Northwest] Page By Well": AnimalWellLocationData("Overworld", "Overworld"),
    "Patrol Cave - Normal Chest": AnimalWellLocationData("Overworld", "Patrol Cave"),
    "Ruined Shop - Chest 1": AnimalWellLocationData("Overworld", "Ruined Shop"),
    "Ruined Shop - Chest 2": AnimalWellLocationData("Overworld", "Ruined Shop"),
    "Ruined Shop - Chest 3": AnimalWellLocationData("Overworld", "Ruined Shop"),
    "Ruined Passage - Page Pickup": AnimalWellLocationData("Overworld", "Ruined Passage"),
    "Shop - Potion 1": AnimalWellLocationData("Overworld", "Shop"),
    "Shop - Potion 2": AnimalWellLocationData("Overworld", "Shop"),
    "Shop - Coin 1": AnimalWellLocationData("Overworld", "Shop"),
    "Shop - Coin 2": AnimalWellLocationData("Overworld", "Shop"),
    "Special Shop - Secret Page Pickup": AnimalWellLocationData("Overworld", "Special Shop"),
    "Stick House - Stick Chest": AnimalWellLocationData("Overworld", "Stick House"),
    "Sealed Temple - Page Pickup": AnimalWellLocationData("Overworld", "Sealed Temple"),
    "Hourglass Cave - Hourglass Chest": AnimalWellLocationData("Overworld", "Hourglass Cave"),
    "Far Shore - Secret Chest": AnimalWellLocationData("Overworld", "Far Shore"),
    "Far Shore - Page Pickup": AnimalWellLocationData("Overworld", "Far Shore to Spawn Region"),
    "Coins in the Well - 10 Coins": AnimalWellLocationData("Overworld", "Overworld", location_group="Well"),
    "Coins in the Well - 15 Coins": AnimalWellLocationData("Overworld", "Overworld", location_group="Well"),
    "Coins in the Well - 3 Coins": AnimalWellLocationData("Overworld", "Overworld", location_group="Well"),
    "Coins in the Well - 6 Coins": AnimalWellLocationData("Overworld", "Overworld", location_group="Well"),
    "Secret Gathering Place - 20 Fairy Reward": AnimalWellLocationData("Overworld", "Secret Gathering Place", location_group="Fairies"),
    "Secret Gathering Place - 10 Fairy Reward": AnimalWellLocationData("Overworld", "Secret Gathering Place", location_group="Fairies"),
    "Overworld - [West] Moss Wall Holy Cross": AnimalWellLocationData("Overworld Holy Cross", "Overworld Holy Cross", location_group="Holy Cross"),
    "Overworld - [Southwest] Flowers Holy Cross": AnimalWellLocationData("Overworld Holy Cross", "Overworld Beach", location_group="Holy Cross"),
    "Overworld - [Southwest] Fountain Holy Cross": AnimalWellLocationData("Overworld Holy Cross", "Overworld Holy Cross", location_group="Holy Cross"),
    "Overworld - [Northeast] Flowers Holy Cross": AnimalWellLocationData("Overworld Holy Cross", "East Overworld", location_group="Holy Cross"),
    "Overworld - [East] Weathervane Holy Cross": AnimalWellLocationData("Overworld Holy Cross", "East Overworld", location_group="Holy Cross"),
    "Overworld - [West] Windmill Holy Cross": AnimalWellLocationData("Overworld Holy Cross", "Overworld Holy Cross", location_group="Holy Cross"),
    "Overworld - [Southwest] Haiku Holy Cross": AnimalWellLocationData("Overworld Holy Cross", "Overworld Beach", location_group="Holy Cross"),
    "Overworld - [West] Windchimes Holy Cross": AnimalWellLocationData("Overworld Holy Cross", "Overworld Holy Cross", location_group="Holy Cross"),
    "Overworld - [South] Starting Platform Holy Cross": AnimalWellLocationData("Overworld Holy Cross", "Overworld Holy Cross", location_group="Holy Cross"),
    "Overworld - [Northwest] Golden Obelisk Page": AnimalWellLocationData("Overworld Holy Cross", "Upper Overworld", location_group="Holy Cross"),
    "Old House - Holy Cross Door Page": AnimalWellLocationData("Overworld Holy Cross", "Old House Back", location_group="Holy Cross"),
    "Cube Cave - Holy Cross Chest": AnimalWellLocationData("Overworld Holy Cross", "Cube Cave", location_group="Holy Cross"),
    "Southeast Cross Door - Chest 3": AnimalWellLocationData("Overworld Holy Cross", "Southeast Cross Room", location_group="Holy Cross"),
    "Southeast Cross Door - Chest 2": AnimalWellLocationData("Overworld Holy Cross", "Southeast Cross Room", location_group="Holy Cross"),
    "Southeast Cross Door - Chest 1": AnimalWellLocationData("Overworld Holy Cross", "Southeast Cross Room", location_group="Holy Cross"),
    "Maze Cave - Maze Room Holy Cross": AnimalWellLocationData("Overworld Holy Cross", "Maze Cave", location_group="Holy Cross"),
    "Caustic Light Cave - Holy Cross Chest": AnimalWellLocationData("Overworld Holy Cross", "Caustic Light Cave", location_group="Holy Cross"),
    "Old House - Holy Cross Chest": AnimalWellLocationData("Overworld Holy Cross", "Old House Front", location_group="Holy Cross"),
    "Patrol Cave - Holy Cross Chest": AnimalWellLocationData("Overworld Holy Cross", "Patrol Cave", location_group="Holy Cross"),
    "Ruined Passage - Holy Cross Chest": AnimalWellLocationData("Overworld Holy Cross", "Ruined Passage", location_group="Holy Cross"),
    "Hourglass Cave - Holy Cross Chest": AnimalWellLocationData("Overworld Holy Cross", "Hourglass Cave Tower", location_group="Holy Cross"),
    "Sealed Temple - Holy Cross Chest": AnimalWellLocationData("Overworld Holy Cross", "Sealed Temple", location_group="Holy Cross"),
    "Fountain Cross Door - Page Pickup": AnimalWellLocationData("Overworld Holy Cross", "Fountain Cross Room", location_group="Holy Cross"),
    "Secret Gathering Place - Holy Cross Chest": AnimalWellLocationData("Overworld Holy Cross", "Secret Gathering Place", location_group="Holy Cross"),
    "Top of the Mountain - Page At The Peak": AnimalWellLocationData("Overworld Holy Cross", "Top of the Mountain", location_group="Holy Cross"),
    "Monastery - Monastery Chest": AnimalWellLocationData("Quarry", "Monastery Back"),
    "Quarry - [Back Entrance] Bushes Holy Cross": AnimalWellLocationData("Quarry Back", "Quarry Back", location_group="Holy Cross"),
    "Quarry - [Back Entrance] Chest": AnimalWellLocationData("Quarry Back", "Quarry Back"),
    "Quarry - [Central] Near Shortcut Ladder": AnimalWellLocationData("Quarry", "Quarry"),
    "Quarry - [East] Near Telescope": AnimalWellLocationData("Quarry", "Quarry"),
    "Quarry - [East] Upper Floor": AnimalWellLocationData("Quarry", "Quarry"),
    "Quarry - [Central] Below Entry Walkway": AnimalWellLocationData("Quarry", "Quarry"),
    "Quarry - [East] Obscured Near Winding Staircase": AnimalWellLocationData("Quarry", "Quarry"),
    "Quarry - [East] Obscured Beneath Scaffolding": AnimalWellLocationData("Quarry", "Quarry"),
    "Quarry - [East] Obscured Near Telescope": AnimalWellLocationData("Quarry", "Quarry"),
    "Quarry - [Back Entrance] Obscured Behind Wall": AnimalWellLocationData("Quarry Back", "Quarry Back"),
    "Quarry - [Central] Obscured Below Entry Walkway": AnimalWellLocationData("Quarry", "Quarry"),
    "Quarry - [Central] Top Floor Overhang": AnimalWellLocationData("Quarry", "Quarry"),
    "Quarry - [East] Near Bridge": AnimalWellLocationData("Quarry", "Quarry"),
    "Quarry - [Central] Above Ladder": AnimalWellLocationData("Quarry", "Quarry Monastery Entry"),
    "Quarry - [Central] Obscured Behind Staircase": AnimalWellLocationData("Quarry", "Quarry"),
    "Quarry - [Central] Above Ladder Dash Chest": AnimalWellLocationData("Quarry", "Quarry Monastery Entry"),
    "Quarry - [West] Upper Area Bombable Wall": AnimalWellLocationData("Quarry Back", "Quarry Back"),
    "Quarry - [East] Bombable Wall": AnimalWellLocationData("Quarry", "Quarry"),
    "Hero's Grave - Ash Relic": AnimalWellLocationData("Quarry", "Hero Relic - Quarry"),
    "Quarry - [West] Shooting Range Secret Path": AnimalWellLocationData("Lower Quarry", "Lower Quarry"),
    "Quarry - [West] Near Shooting Range": AnimalWellLocationData("Lower Quarry", "Lower Quarry"),
    "Quarry - [West] Below Shooting Range": AnimalWellLocationData("Lower Quarry", "Lower Quarry"),
    "Quarry - [Lowlands] Below Broken Ladder": AnimalWellLocationData("Lower Quarry", "Even Lower Quarry"),
    "Quarry - [West] Upper Area Near Waterfall": AnimalWellLocationData("Lower Quarry", "Lower Quarry"),
    "Quarry - [Lowlands] Upper Walkway": AnimalWellLocationData("Lower Quarry", "Even Lower Quarry"),
    "Quarry - [West] Lower Area Below Bridge": AnimalWellLocationData("Lower Quarry", "Lower Quarry"),
    "Quarry - [West] Lower Area Isolated Chest": AnimalWellLocationData("Lower Quarry", "Lower Quarry"),
    "Quarry - [Lowlands] Near Elevator": AnimalWellLocationData("Lower Quarry", "Even Lower Quarry"),
    "Quarry - [West] Lower Area After Bridge": AnimalWellLocationData("Lower Quarry", "Lower Quarry"),
    "Rooted Ziggurat Upper - Near Bridge Switch": AnimalWellLocationData("Rooted Ziggurat", "Rooted Ziggurat Upper Front"),
    "Rooted Ziggurat Upper - Beneath Bridge To Administrator": AnimalWellLocationData("Rooted Ziggurat", "Rooted Ziggurat Upper Back"),
    "Rooted Ziggurat Tower - Inside Tower": AnimalWellLocationData("Rooted Ziggurat", "Rooted Ziggurat Middle Top"),
    "Rooted Ziggurat Lower - Near Corpses": AnimalWellLocationData("Rooted Ziggurat", "Rooted Ziggurat Lower Front"),
    "Rooted Ziggurat Lower - Spider Ambush": AnimalWellLocationData("Rooted Ziggurat", "Rooted Ziggurat Lower Front"),
    "Rooted Ziggurat Lower - Left Of Checkpoint Before Fuse": AnimalWellLocationData("Rooted Ziggurat", "Rooted Ziggurat Lower Front"),
    "Rooted Ziggurat Lower - After Guarded Fuse": AnimalWellLocationData("Rooted Ziggurat", "Rooted Ziggurat Lower Front"),
    "Rooted Ziggurat Lower - Guarded By Double Turrets": AnimalWellLocationData("Rooted Ziggurat", "Rooted Ziggurat Lower Front"),
    "Rooted Ziggurat Lower - After 2nd Double Turret Chest": AnimalWellLocationData("Rooted Ziggurat", "Rooted Ziggurat Lower Front"),
    "Rooted Ziggurat Lower - Guarded By Double Turrets 2": AnimalWellLocationData("Rooted Ziggurat", "Rooted Ziggurat Lower Front"),
    "Rooted Ziggurat Lower - Hexagon Blue": AnimalWellLocationData("Rooted Ziggurat", "Rooted Ziggurat Lower Back", location_group="Bosses"),
    "Ruined Atoll - [West] Near Kevin Block": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll"),
    "Ruined Atoll - [South] Upper Floor On Power Line": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll Ladder Tops"),
    "Ruined Atoll - [South] Chest Near Big Crabs": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll"),
    "Ruined Atoll - [North] Guarded By Bird": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll"),
    "Ruined Atoll - [Northeast] Chest Beneath Brick Walkway": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll"),
    "Ruined Atoll - [Northwest] Bombable Wall": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll"),
    "Ruined Atoll - [North] Obscured Beneath Bridge": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll"),
    "Ruined Atoll - [South] Upper Floor On Bricks": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll Ladder Tops"),
    "Ruined Atoll - [South] Near Birds": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll"),
    "Ruined Atoll - [Northwest] Behind Envoy": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll"),
    "Ruined Atoll - [Southwest] Obscured Behind Fuse": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll"),
    "Ruined Atoll - [East] Locked Room Upper Chest": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll"),
    "Ruined Atoll - [North] From Lower Overworld Entrance": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll Lower Entry Area"),
    "Ruined Atoll - [East] Locked Room Lower Chest": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll"),
    "Ruined Atoll - [Northeast] Chest On Brick Walkway": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll"),
    "Ruined Atoll - [Southeast] Chest Near Fuse": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll Ladder Tops"),
    "Ruined Atoll - [Northeast] Key Pickup": AnimalWellLocationData("Ruined Atoll", "Ruined Atoll"),
    "Cathedral Gauntlet - Gauntlet Reward": AnimalWellLocationData("Swamp", "Cathedral Gauntlet"),
    "Cathedral - Secret Legend Trophy Chest": AnimalWellLocationData("Swamp", "Cathedral Secret Legend Room"),
    "Swamp - [Upper Graveyard] Obscured Behind Hill": AnimalWellLocationData("Swamp", "Swamp Mid"),
    "Swamp - [South Graveyard] 4 Orange Skulls": AnimalWellLocationData("Swamp", "Swamp Front"),
    "Swamp - [Central] Near Ramps Up": AnimalWellLocationData("Swamp", "Swamp Mid"),
    "Swamp - [Upper Graveyard] Near Shield Fleemers": AnimalWellLocationData("Swamp", "Swamp Mid"),
    "Swamp - [South Graveyard] Obscured Behind Ridge": AnimalWellLocationData("Swamp", "Swamp Mid"),
    "Swamp - [South Graveyard] Obscured Beneath Telescope": AnimalWellLocationData("Swamp", "Swamp Front"),
    "Swamp - [Entrance] Above Entryway": AnimalWellLocationData("Swamp", "Back of Swamp Laurels Area"),
    "Swamp - [Central] South Secret Passage": AnimalWellLocationData("Swamp", "Swamp Mid"),
    "Swamp - [South Graveyard] Upper Walkway On Pedestal": AnimalWellLocationData("Swamp", "Swamp Front"),
    "Swamp - [South Graveyard] Guarded By Tentacles": AnimalWellLocationData("Swamp", "Swamp Front"),
    "Swamp - [Upper Graveyard] Near Telescope": AnimalWellLocationData("Swamp", "Swamp Mid"),
    "Swamp - [Outside Cathedral] Near Moonlight Bridge Door": AnimalWellLocationData("Swamp", "Swamp Ledge under Cathedral Door"),
    "Swamp - [Entrance] Obscured Inside Watchtower": AnimalWellLocationData("Swamp", "Swamp Front"),
    "Swamp - [Entrance] South Near Fence": AnimalWellLocationData("Swamp", "Swamp Front"),
    "Swamp - [South Graveyard] Guarded By Big Skeleton": AnimalWellLocationData("Swamp", "Swamp Front"),
    "Swamp - [South Graveyard] Chest Near Graves": AnimalWellLocationData("Swamp", "Swamp Front"),
    "Swamp - [Entrance] North Small Island": AnimalWellLocationData("Swamp", "Swamp Front"),
    "Swamp - [Outside Cathedral] Obscured Behind Memorial": AnimalWellLocationData("Swamp", "Back of Swamp"),
    "Swamp - [Central] Obscured Behind Northern Mountain": AnimalWellLocationData("Swamp", "Swamp Mid"),
    "Swamp - [South Graveyard] Upper Walkway Dash Chest": AnimalWellLocationData("Swamp", "Swamp Mid"),
    "Swamp - [South Graveyard] Above Big Skeleton": AnimalWellLocationData("Swamp", "Swamp Front"),
    "Swamp - [Central] Beneath Memorial": AnimalWellLocationData("Swamp", "Swamp Mid"),
    "Hero's Grave - Feathers Relic": AnimalWellLocationData("Swamp", "Hero Relic - Swamp"),
    "West Furnace - Chest": AnimalWellLocationData("West Garden", "Furnace Walking Path"),
    "Overworld - [West] Near West Garden Entrance": AnimalWellLocationData("West Garden", "Overworld to West Garden from Furnace"),
    "West Garden - [Central Highlands] Holy Cross (Blue Lines)": AnimalWellLocationData("West Garden", "West Garden", location_group="Holy Cross"),
    "West Garden - [West Lowlands] Tree Holy Cross Chest": AnimalWellLocationData("West Garden", "West Garden", location_group="Holy Cross"),
    "West Garden - [Southeast Lowlands] Outside Cave": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [Central Lowlands] Chest Beneath Faeries": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [North] Behind Holy Cross Door": AnimalWellLocationData("West Garden", "West Garden", location_group="Holy Cross"),
    "West Garden - [Central Highlands] Top of Ladder Before Boss": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [Central Lowlands] Passage Beneath Bridge": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [North] Across From Page Pickup": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [Central Lowlands] Below Left Walkway": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [West] In Flooded Walkway": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [West] Past Flooded Walkway": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [North] Obscured Beneath Hero's Memorial": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [Central Lowlands] Chest Near Shortcut Bridge": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [West Highlands] Upper Left Walkway": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [Central Lowlands] Chest Beneath Save Point": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [Central Highlands] Behind Guard Captain": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [Central Highlands] After Garden Knight": AnimalWellLocationData("Overworld", "West Garden after Boss", location_group="Bosses"),
    "West Garden - [South Highlands] Secret Chest Beneath Fuse": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden - [East Lowlands] Page Behind Ice Dagger House": AnimalWellLocationData("West Garden", "West Garden Portal Item"),
    "West Garden - [North] Page Pickup": AnimalWellLocationData("West Garden", "West Garden"),
    "West Garden House - [Southeast Lowlands] Ice Dagger Pickup": AnimalWellLocationData("West Garden", "Magic Dagger House"),
    "Hero's Grave - Effigy Relic": AnimalWellLocationData("West Garden", "Hero Relic - West Garden"),
}

hexagon_locations: Dict[str, str] = {
    "Red Questagon": "Fortress Arena - Siege Engine/Vault Key Pickup",
    "Green Questagon": "Librarian - Hexagon Green",
    "Blue Questagon": "Rooted Ziggurat Lower - Hexagon Blue",
}

location_name_to_id: Dict[str, int] = {name: location_base_id + index for index, name in enumerate(location_table)}

location_name_groups: Dict[str, Set[str]] = {}
for loc_name, loc_data in location_table.items():
    loc_group_name = loc_name.split(" - ", 1)[0]
    location_name_groups.setdefault(loc_group_name, set()).add(loc_name)
    if loc_data.location_group:
        location_name_groups.setdefault(loc_data.location_group, set()).add(loc_name)
