fast_travel_fake = "Fast Travel Mid-Warp"  # for the purpose of not putting all the entrances at the starting region
starting_area = "Squirrel Main"
s_disc_area = "Squirrel S. Medal Area"
starting_after_ghost = "Squirrel After Ghost"
fast_travel = "Fast Travel Room"
fast_travel_fish_teleport = "Fast Travel Fish Teleport Spot"
bird_area = "Bird Area"  # the central portion of the map
bird_capybara_waterfall = "Bird Capybara Waterfall"  # up and right of the ladder
bird_below_mouse_statues = "Bird Below Mouse Statues"  # on the way to frog area, need yoyo
bird_planet_egg_spot = "Bird Planet Egg Spot"
candle_area = "Squirrel Candle Area"
match_above_egg_room = "Match Above Egg Room"  # its own region since you can use the dog elevator
bird_flute_chest = "Bird Flute Chest Room"  # since you can technically get weird with the logic here

fish_upper = "Fish Upper"  # everything prior to the bubble wand chest
fish_lower = "Fish Lower"
fish_boss_1 = "Fish Boss Arena Part 1"  # just the whale
fish_boss_2 = "Fish Boss Arena Part 2"  # whale + seahorse
fish_wand_pit = "Fish B.Wand Chest Pit"
fish_west = "Fish Warp Room"  # after the b. wand chest, rename
fish_tube_room = "Fish Pipe Maze"  # rename?

abyss = "Bone Fish Area"
abyss_lower = "Bone Fish Arena"
uv_lantern_spot = "UV Lantern Spot"

bear_area_entry = "Bear Main Entry"
bear_capybara_and_below = "Bear Main Area"
bear_future_egg_room = "Bear Future Egg Room"
bear_chinchilla_song_room = "Bear Chinchilla Song Room"  # where the bunny is
bear_dark_maze = "Bear Dark Maze"
bear_chameleon_room_1 = "Bear Chameleon Room 1"  # first chameleon encounter with the chinchilla
bear_ladder_after_chameleon = "Bear Ladder after Chameleon 1"
bear_slink_room = "Bear Slink Room"  # the room you get slink
bear_transcendental = "Bear Transcendental Egg Room"
bear_kangaroo_waterfall = "Bear Kangaroo Waterfall and adjacent rooms"  # up left from entry point, need slink
bear_middle_phone_room = "Bear Middle Phone Room"  # after the previous region, has the fast travel, monkey room
bear_crow_rooms = "Bear Crow Rooms"  # the room with a lot of crows, the room with 8 crows, and the room with 4 crows
bear_shadow_egg_spot = "Bear Shadow Egg Chest Spot"  # since you can get here from above with top
bear_hedgehog_square = "Bear Hedgehog on the Square Room"  # the one where the hedgehog presses 4 buttons
bear_connector_passage = "Bear Connector Passage"  # connects capybara save room, upper bear
bear_match_chest_spot = "Bear Match Chest Spot"  # where the match chest is, it's weird okay
bear_upper_phone_room = "Bear Upper Phone Room"
bear_above_chameleon = "Bear Above Chameleon Boss"  # right above the chameleon boss before the flame
bear_chameleon_room_2 = "Bear Chameleon Boss Room before Flame"
bear_razzle_egg_spot = "Bear Razzle Egg Spot"
bear_truth_egg_spot = "Bear Truth Egg Spot"

dog_area = "Dog Main"
dog_chinchilla_skull = "Dog Chinchilla Skull Room"
dog_at_mock_disc = "Dog at Mock Disc Chest"
dog_upper = "Dog Area Upper"  # rename this variable and name
dog_upper_past_lake = "Dog Area Upper past Lake"
dog_upper_above_switch_lines = "Dog Area Upper above Switch Lines"  # rename, that spot where you go up the levels?
dog_upper_above_switch_lines_to_upper_east = "Dog Area Upper above Switch Lines to Upper East"  # where the button is
dog_upper_east = "Dog Area Upper East"  # to the right of the area above the switch lines
bobcat_room = "Bobcat Room"
chest_on_spikes_region = "Chest on Spikes Region"
dog_elevator = "Dog Elevator"  # east of the flame
dog_many_switches = "Dog Switches and Bat"  # west of spike room
dog_upside_down_egg_spot = "Dog Upside Down Egg Spot"
dog_bat_room = "Dog Bat Room"
dog_under_fast_travel_room = "Dog Room under Fast Travel Door Room"
dog_fast_travel_room = "Dog Room with Fast Travel Door"
dog_swordfish_lake_ledge = "Dog Left side of Swordfish Lake"
behind_kangaroo = "Vertical Passage behind Kangaroo Room"
dog_above_fast_travel = "Dog Above Fast Travel Room"  # has some of those breakout blocks
dog_mock_disc_shrine = "Dog Mock Disc Shrine"  # and the rooms to the left of it
kangaroo_room = "Kangaroo Room"
kangaroo_blocks = "Kangaroo Room Blocks"
dog_wheel = "Dog Wheel"  # doggo getting swole af
dog_elevator_upper = "Dog Elevator Upper"  # top of the elevator going up

frog_near_wombat = "Frog Area near Groundhog"  # first part of the frog area after you drop down the hole
frog_under_ostrich_statue = "Frog Area under Ostrich Statue"  # just the dark room basically
frog_pre_ostrich_attack = "Frog before Ostrich Attack"  # left of dark room, right of ostrich, above dynamite
frog_ostrich_attack = "Frog Ostrich Attack"  # and also the little area above it
frog_worm_shaft_top = "Frog Worm Shaft Top"  # where the fire egg is
frog_worm_shaft_bottom = "Frog Worm Shaft Bottom"  # save point after ostrich chase
frog_bird_after_yoyo_1 = "Frog Bird Area after Yoyo 1"  # the first two bird rooms after you get yoyo
frog_bird_after_yoyo_2 = "Frog Bird Area after Yoyo 2"  # the area after the previous one (rewrite comment)
frog_dark_room = "Wave Room"  # the dark room with the frog, and also the wave room
frog_ruby_egg_ledge = "Ruby Egg Ledge"  # the ledge with the ruby egg in the frog dark room
frog_east_of_fast_travel = "Frog East of Fast Travel"  # one screen to the right of the fast travel spot
frog_elevator_and_ostrich_wheel = "Frog Elevator and Ostrich Wheel Section"  # interdependent, so one big region
frog_travel_egg_spot = "Frog Travel Egg Spot"

hippo_entry = "Hippo Entry"  # the beginning of the end
hippo_manticore_room = "Hippo Manticore Room"  # the 4 rooms you evade the manticore in for the first ending
hippo_skull_room = "Hippo Skull Room"  # B. B. Wand and the skull pile
hippo_fireworks = "Hippo Fireworks Room"  # the first ending

home = "Home"
barcode_bunny = "Barcode Bunny"  # barcode bunny is gotten in two places
top_of_the_well = "Top of the Well"  # where the warp song takes you, right of the house
chocolate_egg_spot = "Chocolate Egg Spot"
match_center_well_spot = "Center Well Match Spot"  # in the shaft, across from chocolate egg
